name: Build and Publish Docker Image

on:
  push:
    branches:
      - uat

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: github.repository == 'SeekInvest/BackendNodeJS'
    env:
      IMAGE_NAME: techlabscc/seekinvest-backend:uat
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          file_name: '.env.uat.local'
          envkey_ENVIRONMENT: uat

          # Stripe
          envkey_STRIPE_SECRET_KEY: ${{secrets.UAT_STRIPE_SECRET_KEY}}
          envkey_STRIPE_CHECKOUT_CALLBACK_URL: ${{secrets.UAT_STRIPE_CHECKOUT_CALLBACK_URL}}
          envkey_STRIPE_CHECKOUT_COMPLETE_BILLING_SIGNING_SECRET: ${{secrets.UAT_STRIPE_CHECKOUT_COMPLETE_BILLING_SIGNING_SECRET}}
          envkey_STRIPE_PRODUCT_ID_FOR_MONTHLY_SUBSCRIPTION: ${{secrets.UAT_STRIPE_PRODUCT_ID_FOR_MONTHLY_SUBSCRIPTION}}
          envkey_STRIPE_PRODUCT_ID_FOR_YEARLY_SUBSCRIPTION: ${{secrets.UAT_STRIPE_PRODUCT_ID_FOR_YEARLY_SUBSCRIPTION}}

          # Storage
          envkey_ACCOUNT_KEY: ${{secrets.ACCOUNT_KEY}}
          envkey_ACCOUNT_NAME: ${{secrets.ACCOUNT_NAME}}
          envkey_CONTAINER_NAME: ${{secrets.CONTAINER_NAME}}

          # AUTH0
          envkey_AUTH0_DOMAIN: ${{secrets.UAT_AUTH0_DOMAIN}}
          envkey_AUTH0_CLIENT_ID: ${{secrets.UAT_AUTH0_CLIENT_ID}}
          envkey_AUTH0_CLIENT_SECRET: ${{secrets.UAT_AUTH0_CLIENT_SECRET}}
          envkey_AUTH0_USER_PASSWORD: ${{ secrets.UAT_AUTH0_USER_PASSWORD }}
          envkey_AUTH0_CONNECTION_ID: ${{ secrets.UAT_AUTH0_CONNECTION_ID }}

          # DATABASE
          envkey_DATABASE_URL: ${{ secrets.UAT_DATABASE_URL }}

          # LOG
          envkey_LOG_FORMAT: ${{ env.LOG_FORMAT }}
          envkey_LOG_DIR: ${{ env.LOG_DIR }}

          # SENTRY
          envkey_SENTRY_DSN: ${{ env.SENTRY_DSN }}

          # CORS
          envkey_ORIGIN: ${{ env.ORIGIN }}

          envkey_CREDENTIALS: ${{ env.CREDENTIALS }}

          # PORT
          envkey_PORT: 3000

      - name: Build image
        run: docker build . -f ./Dockerfile.uat -t ${{ env.IMAGE_NAME }}

      - name: Push Image
        run: docker push ${{ env.IMAGE_NAME }}
